name: PR Test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  quality-and-tests:
    name: Code Quality and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux-x64] # 指定 Runtime Identifier
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.200
      - name: Format Check
        run: dotnet format --verify-no-changes
      - name: Run Unit Tests
        run: dotnet test --configuration Release --verbosity normal
      - name: Check AOT Compatibility
        run: |
          # 编译 AOT
          dotnet build Todo.Cli/Todo.Cli.csproj \
            -c Release \
            -r ${{ matrix.rid }} \
            -p:PublishAot=true \
            -p:IsAotCompatible=true \
            -p:EnableAotAnalyzer=true \
            -p:EnableTrimAnalyzer=true \
            -p:EnableSingleFileAnalyzer=true \
            -p:IsTrimmable=true \
            -v detailed \
            > aot_build.log 2>&1
          
          # 解析日志文件，检查警告和错误
          if grep -q "warning IL" aot_build.log; then
            echo "AOT warnings found in build log:"
            grep "warning IL" aot_build.log
            exit 1
          fi
          
          if grep -q "AOT compatibility analyzer" aot_build.log; then
            echo "AOT compatibility analyzer warnings found:"
            grep "AOT compatibility analyzer" aot_build.log
            exit 1
          fi
          
          if grep -q "warning IL2" aot_build.log; then
            echo "Trimming warnings found:"
            grep "warning IL2" aot_build.log
            exit 1
          fi
          
          if grep -q "System.Text.Json.SourceGeneration" aot_build.log; then
            echo "Serialization warnings found:"
            grep "System.Text.Json.SourceGeneration" aot_build.log
            exit 1
          fi
          
          echo "No AOT compatibility issues found."
