name: PR Test
on:
  pull_request:
    branches: [ "main" ]
jobs:
  quality-and-tests:
    name: Code Quality and Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rid: [linux-x64] # 指定 Runtime Identifier
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.200
      - name: Format Check
        run: dotnet format --verify-no-changes
      - name: Run Unit Tests
        run: dotnet test --configuration Release --verbosity normal